/**
 * designTokens.js — Design System Extraction
 * ─────────────────────────────────────────────
 * From a single Lume session, extract a coherent set of design tokens
 * that can be shared across components, exported as theme.js, or used
 * in a broader design system.
 *
 * Philosophy:
 * Every visual decision made in Lume should be extractable as a named value.
 * Colors, radii, shadows — nothing should be hardcoded in consuming code.
 * A junior developer should be able to retheme the entire UI by editing
 * eight lines in theme.js.
 */

// ─── Token extraction ──────────────────────────────────────────────────────────

/**
 * Extract a complete design token set from the current session state.
 *
 * @param {Array}  components  — the styled component array from the copilot
 * @param {object} profile     — the active Copilot profile
 * @returns {object}           — design token object
 */
export function extractTokens(components, profile) {
  if (!profile) return defaultTokens()

  // Gather unique colors from components to detect the actual palette in use
  const borders = unique(components.map(c => c.style?.border).filter(isValidColor))
  const texts   = unique(components.map(c => c.style?.text).filter(isValidColor))

  // Gather radii and shadow flags
  const radii = unique(
    components
      .map(c => c.style?.radius)
      .filter(r => typeof r === 'number'),
  ).sort((a, b) => a - b)

  const hasShadow = components.some(c => c.style?.shadow)

  // Find the primary action color (first button fill, else accent)
  const buttonComponent = components.find(c => c.type === 'Button')
  const primary = buttonComponent?.style?.fill ?? profile.accent ?? '#6366f1'

  // Find the surface color (first card fill, else profile surface)
  const cardComponent = components.find(c => c.type === 'Card')
  const surface = cardComponent?.style?.fill ?? profile.surface ?? '#ffffff'

  // Base radius — smallest non-999 radius in the palette
  const baseRadius = radii.find(r => r < 900) ?? profile.radius ?? 8

  return {
    color: {
      primary,
      primaryText: buttonComponent?.style?.text ?? '#ffffff',
      surface,
      background:  profile.bg ?? '#f4f7fb',
      text:        profile.text ?? '#111827',
      border:      borders[0] ?? '#e2e8f0',
      accent:      profile.accent ?? primary,
      muted:       muteColor(texts[0] ?? '#111827'),
    },
    radius: {
      sm:   Math.max(4,  Math.round(baseRadius * 0.6)),
      md:   baseRadius,
      lg:   Math.round(baseRadius * 1.5),
      full: 9999,
    },
    shadow: {
      sm:   hasShadow ? '0 1px 6px rgba(0,0,0,.06)' : 'none',
      md:   hasShadow ? '0 4px 18px rgba(0,0,0,.12)' : 'none',
      lg:   hasShadow ? '0 8px 32px rgba(0,0,0,.16)' : 'none',
    },
    typography: {
      fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      size: {
        xs:   '11px',
        sm:   '12px',
        base: '13px',
        md:   '14px',
        lg:   '16px',
        xl:   '20px',
      },
      weight: {
        normal:      400,
        medium:      500,
        semibold:    600,
        bold:        700,
        extrabold:   800,
      },
    },
    spacing: {
      xs:  '4px',
      sm:  '8px',
      md:  '12px',
      lg:  '16px',
      xl:  '24px',
      '2xl': '32px',
    },
    transition: {
      fast:     '120ms cubic-bezier(0.2, 0, 0.2, 1)',
      base:     '200ms cubic-bezier(0.4, 0, 0.2, 1)',
      slow:     '350ms cubic-bezier(0.4, 0, 0.2, 1)',
    },
    meta: {
      mood:    profile.mood ?? 'default',
      surface: profile.surface ?? '#ffffff',
    },
  }
}

// ─── Code generation ───────────────────────────────────────────────────────────

/**
 * Render design tokens as an importable JS theme file.
 * @param {object} tokens  — from extractTokens()
 * @returns {string}       — JavaScript source code
 */
export function renderThemeFile(tokens) {
  return `/**
 * theme.js — Design Tokens
 * ─────────────────────────
 * Auto-generated by Lume.
 * Mood: ${tokens.meta.mood}
 *
 * These tokens are the single source of truth for visual style.
 * To retheme the entire UI, modify the values below.
 * Never hardcode a color, radius, or shadow directly in a component.
 */

export const color = ${json(tokens.color)}

export const radius = ${json(tokens.radius)}

export const shadow = ${json(tokens.shadow)}

export const typography = ${json(tokens.typography)}

export const spacing = ${json(tokens.spacing)}

export const transition = ${json(tokens.transition)}

/** Complete token set — import this for convenience */
const theme = { color, radius, shadow, typography, spacing, transition }
export default theme
`
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

function defaultTokens() {
  return extractTokens([], {
    accent:  '#6366f1',
    bg:      '#f4f7fb',
    text:    '#111827',
    surface: '#ffffff',
    radius:  12,
    mood:    'default',
  })
}

function unique(arr) {
  return [...new Set(arr)]
}

function isValidColor(v) {
  return typeof v === 'string' && v.length > 0 && v !== 'transparent'
}

function muteColor(hex) {
  // Appends alpha to make a muted version for secondary text
  return hex + (hex.length === 7 ? '99' : '')
}

function json(obj) {
  return JSON.stringify(obj, null, 2)
    .replace(/"([a-zA-Z][a-zA-Z0-9_]*)"\s*:/g, '$1:') // unquote simple keys
}
